
STOP_TAG = 'stop'
PRESET_SEGMENTS_TAG = 'seg'
PRESET_NAME_TAG = 'n'
ID_TAG = 'id'
SEGMENTS_FILE_TAG = 'segments_file'
COLOR_TAG = 'col'
EFFECT_TAG = 'fx'
EFFECT_NAME_TAG = 'fx_name'
PALETTE_TAG = 'pal'
PALETTE_NAME_TAG = 'pal_name'
SEGMENT_NAME_TAG = 'seg_name'
SEGMENT_TAG = 'seg'
DEFAULTS_TAG = 'defaults'
PRESETS_TAG = 'presets'
PRESET_DEFAULTS = 'preset'
SEGMENT_DEFAULTS = 'segment'
EFFECTS_TAG = 'effects'
DESCRIPTION_TAG = 'desc'
NAME_TAG = 'name'
ALIASES_TAG = 'aliases'
PALETTES_TAG = 'palettes'


INDENT = '  '
DEFAULT_DATA_DIR = '.'
DEFAULT_OUTPUT_DIR = "generated"
DEFAULT_DEFINITIONS_DIR = "etc"
DEFAULT_WLED_DIR = "presets"
DEFAULT_PRESETS_FILE_BASE = "presets"
DEFAULT_PRESETS_FILE_NAME = "{base}.yaml".format(base=DEFAULT_PRESETS_FILE_BASE)
DEFAULT_CFG_FILE_BASE = "cfg"
DEFAULT_CFG_FILE_NAME = "{base}.yaml".format(base=DEFAULT_CFG_FILE_BASE)
DEFAULT_SEGMENTS_FILE_BASE = "segments"
DEFAULT_SEGMENTS_FILE_NAME = "{base}.yaml".format(base=DEFAULT_SEGMENTS_FILE_BASE)
DEFAULT_PROPERTIES_FILE_BASE = "properties"
DEFAULT_PROPERTIES_FILE_NAME = "{base}.yaml".format(base=DEFAULT_PROPERTIES_FILE_BASE)
DEFAULT_COLORS_FILE_BASE = "colors"
DEFAULT_COLORS_FILE_NAME = "{base}.yaml".format(base=DEFAULT_COLORS_FILE_BASE)
DEFAULT_PALETTES_FILE_BASE = "palettes"
DEFAULT_PALETTES_FILE_NAME = "{base}.yaml".format(base=DEFAULT_PALETTES_FILE_BASE)
DEFAULT_EFFECTS_FILE_BASE = "effects"
DEFAULT_EFFECTS_FILE_NAME = "{base}.yaml".format(base=DEFAULT_EFFECTS_FILE_BASE)
DEFAULT_ENVIRONMENT = None

HOST_KEY = "host"
WLED_HOLIDAY_KEY = "wled_holiday"
WLED_YAML2JSON_KEY = "wled_yaml2json"
WLED_UPLOAD_KEY = "wled_upload"
WLED_DIR_KEY = "wled_dir"
DEFINITIONS_DIR_KEY = "definitions_dir"
LIGHTS_FILE_KEY = "lights_file"
DEFAULT_LIGHTS_NAME_KEY = "default_lights_name"
DEFAULT_HOLIDAY_NAME_KEY = "default_holiday_name"
HOLIDAYS_FILE_KEY = "holidays_file"
LIGHTS_KEY = "lights"
HOLIDAY_KEY = "holiday"

NAME_KEY = 'name'
ABBREVIATION_KEY = 'abbr'
INDEX_KEY = 'index'

SEGMENTS_KEY = 'segments'
WLED_NAME_KEY = 'n'
SEGMENT_START_KEY = 'start'
SEGMENT_STOP_KEY = 'stop'
SEGMENT_SPACING_KEY = 'spc'
SEGMENT_GROUPING_KEY = 'grp'
SEGMENT_OFFSET_KEY: str = 'of'
SEGMENT_PATTERN_KEY: str = 'pat'
DEFAULT_SEGMENT_OFFSET = 0
DEFAULT_SEGMENT_GROUPING = 1
DEFAULT_SEGMENT_SPACING = 0

HOLIDAYS_KEY = 'holidays'
NORMALIZED_HOLIDAYS_KEY = 'normalized_holidays'
DEFAULT_HOLIDAYS_FILE = "holidays.yaml"
DEFAULT_LIGHTS_FILE = "holiday_lights.yaml"
DEFAULT_HOLIDAY_NAME = "normal"
DATE_KEY = 'date'
RRULE_KEY = 'rrule'
DAY_OF_YEAR_KEY = 'day_of_year'

PLAYLIST_TAG = 'playlist'
PLAYLIST_PRESETS_TAG = 'ps'
PLAYLIST_PRESETS_PATH_TAG = "{playlist}.{end}".format(playlist=PLAYLIST_TAG, end=PLAYLIST_PRESETS_TAG)
PLAYLIST_END_TAG = 'end'
PLAYLIST_END_PATH_TAG = "{playlist}.{end}".format(playlist=PLAYLIST_TAG, end=PLAYLIST_END_TAG)
PLAYLIST_DURATION_TAG = 'dur'
PLAYLIST_TRANSITION_TAG = 'transition'


